lineNum = 75;
lineUnitLength = 0.0003;
B0 = 0.01;
k = 418.879;
incidentAngle = pi/9;
length = lineNum * lineUnitLength;
sparkLength = 0.003;
dutyCycle = 1;

disk = generateDisk( ...
    'conductor', ...
    lineUnitLength, ...
    length, ...
    sparkLength, ...
    dutyCycle);

figure;
hold;

for i = 0:pi/9 : pi/3
    currentArray = calculateCurrentWithDisk(...
        disk,...
        B0,...
        i,...
        lineUnitLength,...
        k);
    plot(real(currentArray)/max(real(currentArray)))
end